DROP DATABASE IF EXISTS node2micro;
CREATE DATABASE node2micro;
DROP TABLE IF EXISTS `posts`;
CREATE TABLE `posts` (
  `thread` int(11) DEFAULT NULL,
  `text` varchar(1000) DEFAULT NULL,
  `user` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
